### ISSUE TITLE
2 Pin 10k temp sensor 

### ISSUE THREAD

**Issue by Tim2309** [openfancontrol/arguscontroller#2]
Hello
Is ist possible to use standard 10k temp sensors like [this one](https://www.amazon.com/Phobya-Temperature-Sensor-Sleeved-Black/dp/B00EURF6GW) ?

**Comment by openfancontrol** [comment]
Hello,
yes, this is possible. We already had a user who did this.
I can post the code modifications for it, probably tonight or tomorrow.

**Comment by Tim2309** [comment]
This would be great.
Whats about the wiring? One pin to analog, the second to GND? Any resistors to 5V?

**Comment by openfancontrol** [comment]
Yes, probably something like this. Can only give more details when I review and post the code.

**Comment by openfancontrol** [comment]
ok, here is the code from a user who used this sensor:
https://www.alphacool.com/shop/ueberwachung-steuerung/21455/alphacool-eiszapfen-temperatursensor-g1/4-ig/ig-mit-ag-adapter-deep-black

1. comment out all references to tempSensor[], tempSensorPresent[], owPin[]

2. in case AMCMD::CmdGetTemp, instead of
`temperature = tempSensor[i].temperature();`
use
`temperature = getThermistorTemperature()*10;`

3. add this function:
```
int16_t getThermistorTemperature(void) {
  float analogValue = analogRead(PIN_TEMPSENSOR_1);
  
  // Konvertieren des analogen Wertes in ein Widerstandswert
  float resistorValue = (1023 / analogValue)- 1; 
  resistorValue = 10000 / resistorValue;
  double temp = log(((10240000/analogValue) - 10000));
  double kelvin = 1 / (0.001129148 + (0.000234125 * temp) + (0.0000000876741 * temp * temp * temp));
  int16_t celsius = (int16_t) (kelvin - 273.15); 

  return celsius;
}
```

In the alphacool product link, there is the R-T table for it, you have to check this with your device if it has the same R-T relation.
But both are 10k Thermistors, so I would assume no change is needed.

I am currently have no information about a pull-down resistor, but will ask the user. I would assume for now a 10k pull-down is used like here, since the equation is the same:
https://draeger-it.blog/arduino-lektion-84-ntc-widerstand-heissleiter/

Hope this helps.

**Comment by openfancontrol** [comment]
Update:
The user with the alphacool sensor and the code posted above confirmed the pull-down 10k to Ground like this:
```
        __       __
Vcc o--|__|--|--|__|---| Gnd
     10k NTC |  10k R
             |
         Arduino ADC
```

**Comment by Tim2309** [comment]
Thank you.
Do you have a complete ino file with the changes?

step 2 is no problem but where to comment out 1. and add 3. ?

edit: I got it working without step one
One last problem: temp 1-4 are all the same sensor 1. Is it possible to use 4x 10k sensors?

**Comment by openfancontrol** [comment]
Yes, this is possible.
I can commit an alternate sketch with 4x NTC usage, need probably 1-2 days until I have the time.

**Comment by openfancontrol** [comment]
ok, I have updated the example to use NTCs as temperature sensors instead of the default 1-Wire sensors.

For that, just deactivate the line
`#define TEMPERATURE_ONEWIRE`
(and adjust the TEMPSENSOR_COUNT and sensor pins for your hardware.)

Could not test it for myself as I don't have an NTC right now, but the code should work 🙏 . If not, please report back with serial debug output.
Hope that helps.

**Comment by Tim2309** [comment]
I testet it with commenting out the onewire line and activated the debug line
`//#define TEMPERATURE_ONEWIRE`

`#define DEBUG_OUTPUT `

The sensor is wired the same before on 5V and A0 with 10k to GND

The Debug and Argus Monitor didn`t get a temperature:
20:18:23.636 -> Channel 1 temperature: 0
20:18:23.636 -> Channel 2 temperature: 0
20:18:23.636 -> Channel 3 temperature: 0
20:18:23.636 -> Channel 4 temperature: 0

Edit:
I could share a remote desktop with arduino and the connected arduino nano with the sensor for testing if you want.

**Comment by openfancontrol** [comment]
You are right, one thing was missing, this usually happens without one testing the code 😢 
I have fixed that now and tested the code on a Arduino Nano by faking the NTC with a standard resistor (so just 2 resistors with the same value between Vcc and Gnd), which leads to 25C fake temperature, and I can see now this temperature in the debug output. 😄

**Comment by Tim2309** [comment]
Perfect now it works 👍
